### ISSUE TITLE
Subtask: Refine search component based on new desings 

### ISSUE THREAD

**Issue by OttoAhlfors** [EddieTheCubeHead/Stagnum#123]
- [x] Footer overlaps content
- [x] View is not scrollable
- [x] Search card doesn't open on enter
- [x] Search bar highlight corner rounding is smaller diameter than search bar corner rounding
- [x] Disable "add to pool" if the pool is empty

**Comment by EddieTheCubeHead** [comment]
Removed estimate as subtask estimate is included in parent task and thus would be counted twice if the subtask has a numerical estimate.
