### ISSUE TITLE
Subtask: Refine pool component based on new designs

### ISSUE THREAD

**Issue by EddieTheCubeHead** [EddieTheCubeHead/Stagnum#144]
- [ ] Expand collection + child component
- [x] Images are not shown
- [ ] View does not expand when search is hidden
- [x] Delete is not working
- [x] Creating a new pool doesn't reset the content
- [x] Add scroll
